#!/usr/bin/env python
r"""
FData adapter for Invest OS VN.
Reads local FData AmiBroker .dat files.
Observed record format: 40-byte header + 40-byte records, struct <IIfffffII.
"""
from __future__ import annotations
import argparse, json, re, struct
from datetime import datetime, date
from pathlib import Path
from typing import Any, Dict, List, Tuple

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_FDATA = Path(r"C:\Users\DUC\Documents\FDATA")
LIVE = ROOT / "data_live"


def now_iso(): return datetime.now().astimezone().isoformat(timespec="seconds")
def save(path: Path, data: Any):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
def pct(a,b): return round((a/b-1)*100,2) if b else 0.0
def ma(xs,n):
    if not xs: return 0.0
    c=xs[-n:] if len(xs)>=n else xs
    return round(sum(c)/len(c),2)
def rsi(vals,n=14):
    if len(vals)<n+1: return 50.0
    gains=[]; losses=[]
    for i in range(-n,0):
        ch=vals[i]-vals[i-1]; gains.append(max(ch,0)); losses.append(abs(min(ch,0)))
    ag=sum(gains)/n; al=sum(losses)/n
    if al==0: return 100.0
    return round(100-(100/(1+ag/al)),2)
def atr_pct(rows,n=14):
    if len(rows)<2: return 0.0
    trs=[]
    for i in range(max(1,len(rows)-n),len(rows)):
        trs.append(max(rows[i]['high']-rows[i]['low'], abs(rows[i]['high']-rows[i-1]['close']), abs(rows[i]['low']-rows[i-1]['close'])))
    return round((sum(trs)/len(trs))/rows[-1]['close']*100,2) if rows[-1]['close'] else 0.0

def parse_yyyymmdd(s: str) -> date:
    return datetime.strptime(s, '%Y-%m-%d').date()
def days_old(d: str) -> int:
    return (date.today()-parse_yyyymmdd(d)).days

def read_amibroker_dat(path: Path) -> List[Dict[str, Any]]:
    if not path.exists(): return []
    b=path.read_bytes()
    if len(b)<80: return []
    rows=[]; fmt='<IIfffffII'; size=struct.calcsize(fmt)
    for off in range(40, len(b)-size+1, 40):
        try: d,t,o,h,l,c,v,oi,aux=struct.unpack(fmt,b[off:off+size])
        except Exception: continue
        if d<19000101 or d>21000101 or c<=0: continue
        ds=str(d)
        rows.append({'date':f'{ds[:4]}-{ds[4:6]}-{ds[6:8]}','time':int(t),'open':round(float(o),4),'high':round(float(h),4),'low':round(float(l),4),'close':round(float(c),4),'volume':int(float(v)),'open_interest':int(oi)})
    return rows

def parse_symbols(common_dir: Path) -> Dict[str, Dict[str, str]]:
    """Parse protobuf-ish symbols.dat by regex. Enough for ticker/exchange/type/name."""
    p=common_dir/'symbols.dat'
    out={}
    if not p.exists(): return out
    b=p.read_bytes()
    pat=re.compile(rb'\n(.)([A-Z0-9]{2,12})\x1a(.{1,80}?)"([A-Z]{3}|HNX|UPCOM|HSX)\*(.{1,20}?)(?:2\x05stock|2\x02cw|2\x05index)')
    for m in pat.finditer(b):
        ticker=m.group(2).decode('utf-8','ignore')
        name=m.group(3).decode('utf-8','ignore').strip()
        exch=m.group(4).decode('utf-8','ignore')
        code=m.group(5).decode('utf-8','ignore').strip()
        typ='stock' if b'2\x05stock' in m.group(0) else 'cw' if b'2\x02cw' in m.group(0) else 'index'
        out[ticker]={'ticker':ticker,'name':name,'exchange':exch,'type':typ,'code':code}
    # direct fallback for important tickers if regex misses due protobuf variance
    for t in ['VNINDEX','VN30','HNXINDEX','UPINDEX']:
        if t not in out and t.encode() in b: out[t]={'ticker':t,'name':t,'exchange':'INDEX','type':'index','code':''}
    return out

def parse_symbol_info(common_dir: Path, symbols: Dict[str, Dict[str,str]]) -> Dict[str, Dict[str,str]]:
    """Best-effort enrich from symbolInfo.dat: URL + Vietnamese company name."""
    p=common_dir/'symbolInfo.dat'
    if not p.exists(): return symbols
    b=p.read_bytes()
    for ticker, meta in symbols.items():
        if meta.get('type')!='stock': continue
        tb=ticker.encode()
        i=b.find(b'co-phieu/'+tb+b'/tongquan')
        if i!=-1:
            chunk=b[max(0,i-80):i+220]
            meta['url']=f'https://fwt.fialda.com/co-phieu/{ticker}/tongquan'
            # name often follows byte ':' after URL. Decode printable chunk for rough search.
            txt=chunk.decode('utf-8','ignore')
            mm=re.search(r'tongquan:(.{3,80}?)(?:B\x00|J\x07|Vietnam|R\x03)', txt)
            if mm: meta['company_name']=mm.group(1).strip()
    return symbols

def load_metadata(fdata_root: Path) -> Dict[str, Dict[str,str]]:
    # Prefer full decoded metadata generated by scripts/fdata_proto_tool.py
    full = LIVE / 'fdata_symbols_full.json'
    if full.exists():
        try:
            return json.loads(full.read_text(encoding='utf8'))
        except Exception:
            pass
    common=fdata_root/'Common'
    return parse_symbol_info(common, parse_symbols(common))

def bar_from_rows(ticker: str, rows: List[Dict[str,Any]], idx_ret20=0.0, meta=None, raw_path='') -> Dict[str,Any]:
    closes=[r['close'] for r in rows]; vols=[r['volume'] for r in rows]
    last=rows[-1]; prev=rows[-2]
    vol20=sum(vols[-20:])/min(20,len(vols)) if vols else 0
    ret20=pct(closes[-1],closes[-21]) if len(closes)>=21 else 0
    meta=meta or {}
    return {'ticker':ticker,'exchange':meta.get('exchange','VN'),'industry':meta.get('industry','unknown'),'industry_code':meta.get('industry_code',''),'icb_level_1_name':meta.get('icb_level_1_name',''),'icb_level_2_name':meta.get('icb_level_2_name',''),'icb_level_3_name':meta.get('icb_level_3_name',''),'icb_level_4_name':meta.get('icb_level_4_name',''),'date':last['date'],'time':last.get('time',0),'close':last['close'],'change_pct':pct(last['close'],prev['close']),'volume':last['volume'],'vol_ratio_20d':round(last['volume']/vol20,2) if vol20 else 0,'ma20':ma(closes,20),'ma50':ma(closes,50),'ma200':ma(closes,200),'rsi14':rsi(closes,14),'atr14_pct':atr_pct(rows,14),'rs_20d':round((ret20-idx_ret20)/10,2),'raw_path':raw_path}

def fdata_base(fdata_root: Path, timeframe: str) -> Path:
    return fdata_root/'AmiBroker'/timeframe

def index_ret20(base: Path) -> float:
    p=base/'index'/'VNINDEX.dat'
    rows=read_amibroker_dat(p)
    if len(rows)>=21: return pct(rows[-1]['close'], rows[-21]['close'])
    return 0.0

def build_ohlcv_fdata(tickers: List[str], fdata_root: Path, timeframe='EOD') -> Dict[str, Any]:
    base=fdata_base(fdata_root,timeframe); stock_dir=base/'stock'; meta=load_metadata(fdata_root)
    idx_ret=index_ret20(base); bars=[]; warnings=[]
    for t in tickers:
        p=stock_dir/f'{t}.dat'
        rows=read_amibroker_dat(p)
        if len(rows)<2:
            warnings.append(f'{t}: missing_or_insufficient {p}'); continue
        bars.append(bar_from_rows(t, rows, idx_ret, meta.get(t,{}), str(p)))
    return {'as_of':now_iso(),'source':'fdata_amibroker_dat','timeframe':timeframe,'bars':bars,'quality_score':0.96 if bars else 0.0,'warnings':warnings}

def scan_full_market_bars(fdata_root: Path, timeframe='EOD', max_symbols=0) -> Tuple[List[Dict[str,Any]], List[str]]:
    base=fdata_base(fdata_root,timeframe); stock_dir=base/'stock'; meta=load_metadata(fdata_root)
    idx_ret=index_ret20(base); bars=[]; warnings=[]
    files=sorted(stock_dir.glob('*.dat'))
    if max_symbols and max_symbols>0: files=files[:max_symbols]
    for p in files:
        t=p.stem.upper()
        rows=read_amibroker_dat(p)
        if len(rows)<2: continue
        # exclude covered warrants if metadata says not stock
        if meta.get(t,{}).get('type') not in [None,'','stock'] and meta.get(t,{}).get('type')!='stock': continue
        bars.append(bar_from_rows(t, rows, idx_ret, meta.get(t,{}), str(p)))
    if not bars: warnings.append('no_full_market_bars')
    return bars,warnings

def sector_name(bar):
    # Prefer ICB level 2 for market sector grouping; fallback industry.
    return bar.get('icb_level_2_name') or bar.get('industry') or 'Khác'

def build_market_fdata(tickers: List[str], fdata_root: Path, timeframe='EOD', full_market=True, stale_days=3) -> Dict[str, Any]:
    base=fdata_base(fdata_root,timeframe); idx_dir=base/'index'; warnings=[]
    indices=[]
    for sym in ['VNINDEX','VN30','HNXINDEX','UPINDEX','UPCOMINDEX']:
        rows=read_amibroker_dat(idx_dir/f'{sym}.dat')
        if len(rows)<2: continue
        closes=[r['close'] for r in rows]; vols=[r['volume'] for r in rows]
        indices.append({'symbol':sym,'close':closes[-1],'change_pct':pct(closes[-1],closes[-2]),'volume_mn':round(vols[-1]/1_000_000,2),'value_bil_vnd':0,'above_ma20_pct':100.0 if closes[-1]>ma(closes,20) else 0.0,'date':rows[-1]['date']})
    if full_market:
        bars, w = scan_full_market_bars(fdata_root,timeframe); warnings += w
    else:
        bars = build_ohlcv_fdata(tickers,fdata_root,timeframe)['bars']
    adv=sum(1 for b in bars if b['change_pct']>0); dec=sum(1 for b in bars if b['change_pct']<0); unch=max(0,len(bars)-adv-dec)
    nh20=sum(1 for b in bars if b['close']>=b['ma20'] and b['ma20']>0)
    nl20=sum(1 for b in bars if b['close']<b['ma20'] and b['ma20']>0)
    buckets={}
    for b in bars: buckets.setdefault(sector_name(b),[]).append(b)
    sectors=[]
    for sec,xs in buckets.items():
        sectors.append({'name':sec,'count':len(xs),'change_pct':round(sum(x['change_pct'] for x in xs)/len(xs),2),'value_bil_vnd':0,'relative_strength_20d':round(sum(x['rs_20d'] for x in xs)/len(xs),2),'advancers':sum(1 for x in xs if x['change_pct']>0),'decliners':sum(1 for x in xs if x['change_pct']<0)})
    sectors.sort(key=lambda s:(s['relative_strength_20d'],s['change_pct'],s['count']), reverse=True)
    last_dates=[b['date'] for b in bars]
    last_date=max(last_dates) if last_dates else None
    stale=False
    if last_date and days_old(last_date)>stale_days:
        stale=True; warnings.append(f'stale_eod_data: last_date={last_date}, days_old={days_old(last_date)}')
    return {'as_of':now_iso(),'source':'fdata_amibroker_dat','market':'VN','timeframe':timeframe,'last_data_date':last_date,'stale':stale,'universe_size':len(bars),'indices':indices,'breadth':{'advancers':adv,'decliners':dec,'unchanged':unch,'above_ma20':nh20,'below_ma20':nl20,'new_high_20d':None,'new_low_20d':None},'sectors':sectors,'foreign_flow':{'net_value_bil_vnd':0,'top_buy':[],'top_sell':[],'note':'not_in_fdata_dat'},'derivatives':{'vn30f1m_basis':0,'open_interest':0,'note':'not_in_eod_stock_adapter'},'quality_score':0.94 if bars and not stale else 0.72 if bars else 0.0,'warnings':warnings+['foreign_flow_not_available']}

def build_with_stale_fallback(tickers: List[str], fdata_root: Path, stale_days:int):
    eod=build_market_fdata(tickers,fdata_root,'EOD',True,stale_days)
    ohlcv=build_ohlcv_fdata(tickers,fdata_root,'EOD')
    if eod.get('stale'):
        base15=fdata_base(fdata_root,'15m')
        if base15.exists():
            m15=build_market_fdata(tickers,fdata_root,'15m',True,stale_days=9999)
            q15=build_ohlcv_fdata(tickers,fdata_root,'15m')
            m15['fallback_reason']='EOD stale; using 15m'
            q15['fallback_reason']='EOD stale; using 15m'
            return m15,q15
    return eod,ohlcv

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument('--root',default=str(DEFAULT_FDATA))
    ap.add_argument('--tickers',default='FPT,MWG,VCB,SSI')
    ap.add_argument('--timeframe',default='EOD',choices=['EOD','15m','5m','1m'])
    ap.add_argument('--all',action='store_true'); ap.add_argument('--ohlcv',action='store_true'); ap.add_argument('--market',action='store_true')
    ap.add_argument('--full-market',action='store_true',default=True)
    ap.add_argument('--stale-days',type=int,default=3)
    ap.add_argument('--fallback-intraday',action='store_true')
    args=ap.parse_args()
    root=Path(args.root); tickers=[x.strip().upper() for x in args.tickers.split(',') if x.strip()]
    if args.fallback_intraday:
        market,ohlcv=build_with_stale_fallback(tickers,root,args.stale_days)
        if args.all or args.market: p=LIVE/'market_snapshot.vn.json'; save(p,market); print('wrote',p)
        if args.all or args.ohlcv: p=LIVE/'ohlcv_sample.vn.json'; save(p,ohlcv); print('wrote',p)
        return
    if args.all or args.ohlcv:
        p=LIVE/'ohlcv_sample.vn.json'; save(p, build_ohlcv_fdata(tickers,root,args.timeframe)); print('wrote',p)
    if args.all or args.market:
        p=LIVE/'market_snapshot.vn.json'; save(p, build_market_fdata(tickers,root,args.timeframe,args.full_market,args.stale_days)); print('wrote',p)
if __name__=='__main__': main()
