#!/usr/bin/env python
r"""
HOSE full listed breadth from FData, no liquidity filter.
Input: data_live/fdata_hose_all_bars.json generated by fdata_hose_universe.py
"""
from __future__ import annotations
import argparse, json
from collections import defaultdict
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List

ROOT=Path(__file__).resolve().parents[1]
LIVE=ROOT/'data_live'
OUT=ROOT/'outputs'

def save(p:Path,x:Any):
    p.parent.mkdir(parents=True,exist_ok=True)
    p.write_text(json.dumps(x,ensure_ascii=False,indent=2),encoding='utf-8')

def md_table(headers, rows):
    out=["| "+" | ".join(headers)+" |", "| "+" | ".join(["---"]*len(headers))+" |"]
    for r in rows: out.append("| "+" | ".join(map(str,r))+" |")
    return "\n".join(out)

def fmt_pct(x): return f"{x:.2f}%"
def load_market_snapshot()->Dict[str,Any]:
    p=LIVE/'market_snapshot.vn.json'
    if not p.exists(): return {}
    try: return json.loads(p.read_text(encoding='utf-8'))
    except Exception: return {}

def group_stats(bars:List[Dict[str,Any]], key:str)->List[Dict[str,Any]]:
    buckets=defaultdict(list)
    for b in bars: buckets[b.get(key) or 'unknown'].append(b)
    rows=[]
    for name,xs in buckets.items():
        adv=sum(1 for x in xs if x['change_pct']>0); dec=sum(1 for x in xs if x['change_pct']<0); unch=len(xs)-adv-dec
        above=sum(1 for x in xs if x.get('ma20') and x['close']>=x['ma20']); below=sum(1 for x in xs if x.get('ma20') and x['close']<x['ma20'])
        rows.append({'name':name,'count':len(xs),'advancers':adv,'decliners':dec,'unchanged':unch,'adv_dec_ratio':round(adv/max(1,dec),2),'avg_change_pct':round(sum(x['change_pct'] for x in xs)/len(xs),2),'above_ma20':above,'below_ma20':below,'above_ma20_pct':round(above/max(1,above+below)*100,2),'avg_rs20':round(sum(x['rs_20d'] for x in xs)/len(xs),2),'total_volume':sum(x['volume'] for x in xs)})
    rows.sort(key=lambda r:(r['avg_rs20'],r['avg_change_pct'],r['adv_dec_ratio'],r['count']), reverse=True)
    return rows

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--input',default=str(LIVE/'fdata_hose_all_bars.json')); ap.add_argument('--top',type=int,default=30)
    args=ap.parse_args(); data=json.loads(Path(args.input).read_text(encoding='utf-8')); bars=data.get('bars',[])
    market_snapshot=load_market_snapshot()
    indices=market_snapshot.get('indices',[]) if market_snapshot else []
    adv=sum(1 for b in bars if b['change_pct']>0); dec=sum(1 for b in bars if b['change_pct']<0); unch=len(bars)-adv-dec
    above=sum(1 for b in bars if b.get('ma20') and b['close']>=b['ma20']); below=sum(1 for b in bars if b.get('ma20') and b['close']<b['ma20'])
    sector=group_stats(bars,'icb_level_2_name'); industry=group_stats(bars,'industry')
    zero=sum(1 for b in bars if b.get('volume',0)==0); lowvol=sum(1 for b in bars if b.get('volume',0)<50000)
    up=sorted(bars,key=lambda b:b['change_pct'],reverse=True)[:args.top]; dn=sorted(bars,key=lambda b:b['change_pct'])[:args.top]
    result={'as_of':datetime.now().astimezone().isoformat(timespec='seconds'),'source':'fdata_hose_all_breadth','input':args.input,'exchange':'HOSE','universe_size':len(bars),'market':{'indices':indices,'source':market_snapshot.get('source') if market_snapshot else None,'as_of':market_snapshot.get('as_of') if market_snapshot else None},'breadth':{'advancers':adv,'decliners':dec,'unchanged':unch,'adv_dec_ratio':round(adv/max(1,dec),2),'above_ma20':above,'below_ma20':below,'above_ma20_pct':round(above/max(1,above+below)*100,2),'zero_volume':zero,'low_volume_lt_50000':lowvol},'sector_breadth':sector,'industry_breadth':industry,'top_gainers':up,'top_losers':dn,'metadata':{k:data.get(k) for k in ['listed_symbols_count','bars_count','missing_dat_count','insufficient_count','last_dates']}}
    save(OUT/'fdata_hose_breadth.json',result)
    md='# HOSE Full Listed Breadth — No Liquidity Filter\n\n'
    md+=f"As of: {result['as_of']}\n\nUniverse: {len(bars)} HOSE symbols\n\n"
    if indices:
        md+='## Index context\n'+md_table(['Index','Date','Close','%','Volume mn','Above MA20'],[[x.get('symbol'),x.get('date') or x.get('as_of',''),x.get('close'),fmt_pct(x.get('change_pct',0)),x.get('volume_mn'),x.get('above_ma20_pct')] for x in indices])+'\n\n'
    br=result['breadth']; md+=md_table(['Metric','Value'],[['Advancers',br['advancers']],['Decliners',br['decliners']],['Unchanged',br['unchanged']],['A/D',br['adv_dec_ratio']],['Above MA20',br['above_ma20']],['Below MA20',br['below_ma20']],['Above MA20 %',fmt_pct(br['above_ma20_pct'])],['Zero volume',br['zero_volume']],['Volume < 50k',br['low_volume_lt_50000']]])
    md+='\n\n## Sector breadth\n'+md_table(['Sector','Count','Adv','Dec','A/D','Avg %','RS20','Above MA20 %'],[[r['name'],r['count'],r['advancers'],r['decliners'],r['adv_dec_ratio'],fmt_pct(r['avg_change_pct']),r['avg_rs20'],fmt_pct(r['above_ma20_pct'])] for r in sector])
    md+='\n\n## Top gainers\n'+md_table(['Ticker','Industry','%','Close','Volume'],[[b['ticker'],b.get('industry',''),fmt_pct(b['change_pct']),b['close'],b['volume']] for b in up])
    md+='\n\n## Top losers\n'+md_table(['Ticker','Industry','%','Close','Volume'],[[b['ticker'],b.get('industry',''),fmt_pct(b['change_pct']),b['close'],b['volume']] for b in dn])
    (OUT/'fdata_hose_breadth.md').write_text(md,encoding='utf-8')
    print('OK HOSE breadth'); print(OUT/'fdata_hose_breadth.json'); print(OUT/'fdata_hose_breadth.md')
if __name__=='__main__': main()
